# fly.toml app configuration file generated for battery-charger-ecommerce-misty-shape-8893 on 2024-11-01T14:31:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'battery-charger-ecommerce-misty-shape-8893'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
